import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: {
    minHeight: '100vh',
    background: 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
  },
  card: {
    width: '100%',
    maxWidth: 420,
    background: '#ffffff',
    borderRadius: 20,
    padding: 28,
    boxShadow: '0 20px 60px rgba(0,0,0,0.3)',
    position: 'relative' as const,
  },
  header: {
    textAlign: 'center' as const,
    paddingBottom: 16,
    marginBottom: 16,
    borderBottom: '1px solid #e2e8f0',
  },
  logo: {
    fontSize: 11,
    fontWeight: 800,
    color: '#3b82f6',
    letterSpacing: '0.2em',
    textTransform: 'uppercase' as const,
  },
  osNumber: {
    fontSize: 22,
    fontWeight: 900,
    color: '#1e293b',
    letterSpacing: '-0.5px',
    marginTop: 2,
  },
  statusSection: {
    textAlign: 'center' as const,
    marginBottom: 20,
  },
  statusLabel: {
    fontSize: 10,
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.15em',
    color: '#94a3b8',
    marginBottom: 8,
  },
  statusBadge: {
    display: 'inline-block',
    padding: '8px 24px',
    borderRadius: 40,
    fontSize: 16,
    fontWeight: 800,
  },
  readyBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    background: '#ecfdf5',
    border: '1px solid #a7f3d0',
    borderRadius: 12,
    padding: '12px 16px',
    marginBottom: 20,
    fontSize: 13,
    color: '#065f46',
  },
  section: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 10,
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.12em',
    color: '#94a3b8',
    marginBottom: 8,
  },
  infoGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 8,
  },
  infoItem: {
    background: '#f8fafc',
    borderRadius: 8,
    padding: '8px 12px',
    border: '1px solid #f1f5f9',
  },
  infoLabel: {
    display: 'block',
    fontSize: 9,
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    color: '#94a3b8',
    letterSpacing: '0.08em',
    marginBottom: 2,
  },
  infoValue: {
    display: 'block',
    fontSize: 13,
    fontWeight: 600,
    color: '#1e293b',
  },
  problemBox: {
    background: '#fef2f2',
    border: '1px solid #fecaca',
    borderLeft: '3px solid #ef4444',
    borderRadius: 8,
    padding: '10px 14px',
    fontSize: 13,
    fontWeight: 500,
    color: '#1e293b',
    lineHeight: 1.4,
  },
  datesRow: {
    display: 'flex',
    gap: 10,
    marginBottom: 16,
  },
  dateCard: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    padding: '12px 10px',
    background: '#f0fdf4',
    border: '1px solid #bbf7d0',
    borderRadius: 12,
    textAlign: 'center' as const,
  },
  dateIcon: {
    fontSize: 20,
    marginBottom: 4,
  },
  dateLabel: {
    display: 'block',
    fontSize: 9,
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    color: '#16a34a',
    letterSpacing: '0.08em',
    marginBottom: 4,
  },
  dateValue: {
    display: 'block',
    fontSize: 15,
    fontWeight: 800,
    color: '#14532d',
  },
  photoGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 8,
  },
  photo: {
    width: '100%',
    borderRadius: 8,
    border: '1px solid #e2e8f0',
    aspectRatio: '1',
    objectFit: 'cover' as const,
  },
  actions: {
    marginTop: 20,
  },
  whatsappBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    width: '100%',
    padding: '14px 20px',
    background: '#25D366',
    color: '#fff',
    border: 'none',
    borderRadius: 12,
    fontSize: 14,
    fontWeight: 700,
    textDecoration: 'none',
    cursor: 'pointer',
  },
  footer: {
    marginTop: 20,
    textAlign: 'center' as const,
    fontSize: 10,
    color: '#94a3b8',
    letterSpacing: '0.08em',
  },
  input: {
    flex: 1,
    padding: '12px 16px',
    border: '2px solid #e2e8f0',
    borderRadius: 12,
    fontSize: 16,
    fontWeight: 600,
    color: '#1e293b',
    outline: 'none',
  },
  searchBtn: {
    padding: '12px 24px',
    background: '#3b82f6',
    color: '#fff',
    border: 'none',
    borderRadius: 12,
    fontSize: 14,
    fontWeight: 700,
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
  },
  errorBox: {
    marginTop: 12,
    padding: '10px 14px',
    background: '#fef2f2',
    border: '1px solid #fecaca',
    borderRadius: 8,
    color: '#dc2626',
    fontSize: 13,
    fontWeight: 500,
    textAlign: 'center' as const,
  },
  spinner: {
    fontSize: 32,
    textAlign: 'center' as const,
    animation: 'spin 0.8s linear infinite',
    margin: '0 auto',
  },
};

if (typeof document !== 'undefined') {
  const existing = document.getElementById('pkeyframes');
  if (!existing) {
    const s = document.createElement('style');
    s.id = 'pkeyframes';
    s.textContent = `@keyframes spin { to { transform: rotate(360deg); } }`;
    document.head.appendChild(s);
  }
}