FROM node:22-slim

WORKDIR /app

ENV NODE_ENV=development

RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
COPY prisma ./prisma
RUN npm ci

COPY . .

EXPOSE 3000 5173
CMD ["npm", "run", "dev"]
